require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
  Include:
    - '**/*.axlsx'
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Documentation:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: beginning_only

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/ClassAndModuleChildren:
  AutoCorrect: true
  EnforcedStyle: compact

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/AndOr:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

Style/RescueModifier:
  Enabled: false
